# Generated by Django 2.2.6 on 2019-10-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, help_text='Any instructions people need to use this note app.', null=True),
        ),
    ]
